// Generate the offline SVG basemap for the journey maps (src/web/basemap.generated.js).
//
// Source: Natural Earth 1:110m admin-0 countries (public domain). We clip every
// country ring to the flyway region this roster uses, drop coordinate precision
// to ~1 km, and emit plain [lon,lat] rings + a per-ring bbox (for cheap render-
// time culling). No runtime dependency ships — the output is static geometry,
// exactly like real-tracks.generated.ts. Re-run: `node scripts/build-basemap.mjs`.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SRC =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson";

// Generous clip box: larger than any track's extent so clip-introduced edges are
// always off-window (SVG clips them) and never render as spurious straight lines.
const CLIP = { xmin: -30, xmax: 45, ymin: -5, ymax: 65 };
const PRECISION = 2; // decimals (~1.1 km) — plenty for a schematic basemap

function intersect(a, b, axis, val) {
  const t = (val - a[axis]) / (b[axis] - a[axis]);
  return [a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1])];
}

/** Sutherland–Hodgman clip of a ring against the rectangle (convex region). */
function clipRing(ring, c) {
  const stages = [
    { inside: (p) => p[0] >= c.xmin, axis: 0, val: c.xmin },
    { inside: (p) => p[0] <= c.xmax, axis: 0, val: c.xmax },
    { inside: (p) => p[1] >= c.ymin, axis: 1, val: c.ymin },
    { inside: (p) => p[1] <= c.ymax, axis: 1, val: c.ymax },
  ];
  let out = ring;
  for (const s of stages) {
    const input = out;
    out = [];
    if (input.length === 0) break;
    for (let i = 0; i < input.length; i++) {
      const cur = input[i];
      const prev = input[(i + input.length - 1) % input.length];
      const curIn = s.inside(cur);
      const prevIn = s.inside(prev);
      if (curIn) {
        if (!prevIn) out.push(intersect(prev, cur, s.axis, s.val));
        out.push(cur);
      } else if (prevIn) {
        out.push(intersect(prev, cur, s.axis, s.val));
      }
    }
  }
  return out;
}

const round = (v) => Math.round(v * 10 ** PRECISION) / 10 ** PRECISION;

/** Shoelace area (deg²) — to drop slivers the eye can't see at this scale. */
function area(ring) {
  let a = 0;
  for (let i = 0; i < ring.length; i++) {
    const p = ring[i];
    const q = ring[(i + 1) % ring.length];
    a += p[0] * q[1] - q[0] * p[1];
  }
  return Math.abs(a) / 2;
}

function* ringsOf(geom) {
  if (!geom) return;
  if (geom.type === "Polygon") yield* geom.coordinates;
  else if (geom.type === "MultiPolygon") for (const poly of geom.coordinates) yield* poly;
}

async function main() {
  console.error(`fetching ${SRC}`);
  const res = await fetch(SRC);
  if (!res.ok) throw new Error(`source HTTP ${res.status}`);
  const gj = await res.json();

  const polys = [];
  for (const f of gj.features) {
    for (const ring of ringsOf(f.geometry)) {
      const clipped = clipRing(ring, CLIP);
      if (clipped.length < 4) continue;
      if (area(clipped) < 0.05) continue; // ~drop sub-pixel islands
      const r = clipped.map((p) => [round(p[0]), round(p[1])]);
      let minLon = Infinity, minLat = Infinity, maxLon = -Infinity, maxLat = -Infinity;
      for (const [lon, lat] of r) {
        if (lon < minLon) minLon = lon;
        if (lon > maxLon) maxLon = lon;
        if (lat < minLat) minLat = lat;
        if (lat > maxLat) maxLat = lat;
      }
      polys.push({ b: [minLon, minLat, maxLon, maxLat], r });
    }
  }
  polys.sort((a, b) => area(b.r) - area(a.r)); // big landmasses first (drawn under)

  const pts = polys.reduce((n, p) => n + p.r.length, 0);
  const body =
    "// GENERATED by scripts/build-basemap.mjs — do not edit. Natural Earth 1:110m\n" +
    "// admin-0 countries (public domain), clipped to the flyway region. Each entry:\n" +
    "// { b:[minLon,minLat,maxLon,maxLat], r:[[lon,lat],...] }. Static geometry only.\n" +
    "export const LAND = [\n" +
    polys
      .map((p) => `  {b:[${p.b.join(",")}],r:${JSON.stringify(p.r)}},`)
      .join("\n") +
    "\n];\n";

  const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "web", "basemap.generated.js");
  await writeFile(outPath, body, "utf8");
  console.error(`wrote ${outPath}: ${polys.length} rings, ${pts} points, ${(body.length / 1024).toFixed(0)} KB`);
}

main().catch((e) => {
  console.error("FAILED", e);
  process.exit(1);
});
